### ISSUE TITLE
Adding date and timer in To-Do-List

### ISSUE THREAD

**Issue by Mahekjain2706** [avinash201199/To-Do-List#106]
I want to add the timer and date that we can fix for each task. if time is overs and the task is not completed marked by red else complete is marked add green and also we remove the completed task.

**Comment by Mahekjain2706** [comment]
Hey, I want to solve this issue, can you assign me this issue?

**Comment by Mahekjain2706** [comment]
Hey, I want to add this feature, Can you assign me?

**Comment by avinash201199** [comment]
> Hey, I want to add this feature, Can you assign me?

go ahead :)

**Comment by Mahekjain2706** [comment]
Hey @avinash201199, I am very sorry because now I can't able to complete it. So can you give it to anyone else?

**Comment by AdithiDesai** [comment]
Hey @avinash201199 , I want to work on this issue. Can you assign it to me?

**Comment by Rajnish-bhagat** [comment]
Hey @avinash201199 , I can do it well. Could you assign it to me?
