### ISSUE TITLE
Add responsive footer

### ISSUE THREAD

**Issue by supminn** [avinash201199/To-Do-List#11]
Create a footer that provides the details about the app as well as links to your social media.

**Comment by supminn** [comment]
I would like to work on this issue.

**Comment by avinash201199** [comment]
insta-https://www.instagram.com/lets__code/
linkedin-https://www.linkedin.com/in/avinash-singh-071b79175/
email-avinash201199gmail.com

**Comment by Prajit-Sengupta** [comment]
Hey, have sent a PR for Hacktoberfest. Have added a responsive PR.  Do check it out! Thanks!

**Comment by avinash201199** [comment]
> Hey, have sent a PR for Hacktoberfest. Have added a responsive PR. Do check it out! Thanks!

someone is already assigned with this issue , please create your own issue
