### ISSUE TITLE
Edit feature not working as expected

### ISSUE THREAD

**Issue by codeswithroh** [avinash201199/To-Do-List#118]
After editing a todo item, user is not allowed to view the changes unless and until they refresh. 

Recommended action:
After editing a todo item, an icon should be present to confirm with the user about the changes they made and on clicking that the user will be able to see the todo-item card with the new text.

**Comment by ayush-Sharma173** [comment]
@avinash201199 Please assign this issue to me.

**Comment by ayush-Sharma173** [comment]
> @avinash201199 Please assign this issue to me.

I have created a PR.
