### ISSUE TITLE
Dark Mode Feature 🌙

### ISSUE THREAD

**Issue by AjayMaheshwari23** [avinash201199/To-Do-List#123]
I want to add a toggle button for switching between dark and light mode . 
Some users prefer viewing the website in dark mode for better visibility and readability . 
can you assign it to me .

**Comment by anivaish** [comment]
Ya sure I can do it. Please Assign this issue to me.I will resolve this issue as early as I can.

**Comment by anivaish** [comment]
please have a look @avinash201199 on the code changes and please merge it. Thank you

**Comment by Datalog-Mindhack** [comment]
@avinash201199  I have already created PR for this issue, kindly look into it.
