### ISSUE TITLE
Designing a logo 

### ISSUE THREAD

**Issue by Vanshiii203** [avinash201199/To-Do-List#127]

**Comment by akankshsinhaa** [comment]
Hey there Vanshi, what exactly do you want your logo to look like?

**Comment by Vanshiii203** [comment]
> Hey there Vanshi, what exactly do you want your logo to look like?
hey @akankshsinhaa, please check the image below.
![logo](https://user-images.githubusercontent.com/94471189/193776764-f253b2af-2f13-4446-9611-d0e2496ee847.png)

**Comment by akankshsinhaa** [comment]
@Vanshiii203 The design's really nice. Would you be open to the idea of a more minimalist logo design with the same colour scheme?

**Comment by SuryanshSinha2612** [comment]
@Vanshiii203 Hey there Vanshi, I have just done some color changes please give your review on it😊
https://www.canva.com/design/DAFOELOaOcY/yyZ_SDCAxilYdxl12RXCig/edit?utm_content=DAFOELOaOcY&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by Vanshiii203** [comment]
> @Vanshiii203 The design's really nice. Would you be open to the idea of a more minimalist logo design with the same colour scheme?

Thanks for your appreciation, Can you please give me some samples?

**Comment by SuryanshSinha2612** [comment]
Are you with new projects for this hacktoberfest??
