### ISSUE TITLE
Action icons should have title attribute to improve UX

### ISSUE THREAD

**Issue by vikrammahto** [avinash201199/To-Do-List#164]
Adding title in icons will specify that what action will happen if we click on those.

![To-Do-List](https://user-images.githubusercontent.com/47027476/194501573-8db3fe9c-9d22-46b9-ab1a-e6cbcc443cbd.png)

**Comment by vikrammahto** [comment]
Please assign me this task if you find this issue valuable.

**Comment by revati-deshmukh** [comment]
Can you assign this task to me?
