### ISSUE TITLE
Different styling for primary and secondary buttons

### ISSUE THREAD

**Issue by vikrammahto** [avinash201199/To-Do-List#165]
In delete all modal, yes and no buttons should have different styling to indicate the actions. 

![To-Do-List (1)](https://user-images.githubusercontent.com/47027476/194502723-09c73ba3-5926-4d52-bf96-22a3fa13d34c.png)

**Comment by vikrammahto** [comment]
Please assign task to me.

**Comment by revati-deshmukh** [comment]
I would like to do this. May I?
