### ISSUE TITLE
Fix empty tasks getting added

### ISSUE THREAD

**Issue by abee62** [avinash201199/To-Do-List#2]
Empty tasks are also getting added to the list. I would like to work on this. Could you please assign this issue to me @avinash201199 ?
I would like to contribute as a part of hacktoberfest2021.

**Comment by avinash201199** [comment]
@go ahead, don't forget to add the screen shot while making pr

**Comment by abee62** [comment]
> @go ahead, don't forget to add the screen shot while making pr

What screen shot?

**Comment by avinash201199** [comment]
> > @go ahead, don't forget to add the screen shot while making pr
> 
> What screen shot?

nothing ignore, you can work further on the UI/UX or some feature
