### ISSUE TITLE
The status filter  dropdown disappears on small screen size 

### ISSUE THREAD

**Issue by Shubh-2402** [avinash201199/To-Do-List#21]
I would like to fix this issue so that the filter functionality can be used on mobiles as well. Plz assign me this issue

**Comment by Harshverma9140** [comment]
#22 is my PR. I've fixed the required , issue please accept my pull request.

Accept the Pull request and merge it for hacktoberfest.

#hacktoberfest

**Comment by Shubh-2402** [comment]
My pr is #23 .  I have fixed the issue and attached the screenshot to my PR . Please accept my PR and merge it for hacktoberfest.
