### ISSUE TITLE
Remove overlap of toggle button 

### ISSUE THREAD

**Issue by Vanshiii203** [avinash201199/To-Do-List#259]
![Screenshot_2022-10-19-06-53-51-91_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/94471189/196575523-09094947-a8a5-4306-b24b-671044a33c70.jpg)

**Comment by VTHARUN01** [comment]
Please assign me this issue

**Comment by avinash201199** [comment]
@Vanshiii203  hey , you have already contributed a lot in this repo , please contribute in another repo also , they review every pr so having many pr in same repo is not advised :)

Thank you
