### ISSUE TITLE
Feature Request: Add Confirmation Dialog for Task Deletion

### ISSUE THREAD

**Issue by Divjot02** [avinash201199/To-Do-List#312]
### Description:
This feature request is about adding a confirmation dialog box that pops up when a user clicks the "Trash-icon" on todo-item. 

- **Current Behavior:** Currently, in the to-do list application, when a user clicks on the "Trash-icon" to remove a task, there is _**no confirmation step**_. This can lead to unintentional task deletion, which could result in data loss.
 
[_**Video**_](https://github.com/avinash201199/To-Do-List/assets/140320635/b762ca88-d4ea-44bc-831b-38b7479ba7a2)

- **Desired Behavior:** I propose adding a confirmation dialog for task deletion. When a user clicks the "Trash-icon" a dialog should appear, asking them to confirm whether they want to delete the task. This will provide users with an additional layer of protection against accidental deletions.

**Use Case:**
- When managing a lengthy list of tasks, it is easy to mistakenly click the "Delete" button.
- The confirmation dialog will provide a _**simple way to double-check**_ before deleting a task.

### Implementation Details:

The confirmation dialog can be implemented using JavaScript and CSS. It will be displayed when the "Trash-icon" is clicked and include options to confirm or cancel the deletion.

**Additional Information:**

This feature will enhance the user experience and reduce the risk of unintentional task deletions.
It's a common practice in task management applications to have a confirmation step for critical actions like task deletion.

**Comment by Divjot02** [comment]
Hey @avinash201199 , please consider implementing this feature as it will be a valuable addition to the application.
If you have any questions/suggestions or need more details, please feel free to reach out.

Also, would you please allow me to implement this feature by assigning this to me?

**Comment by avinash201199** [comment]
> Hey @avinash201199 , please consider implementing this feature as it will be a valuable addition to the application. If you have any questions/suggestions or need more details, please feel free to reach out.
> 
> Also, would you please allow me to implement this feature by assigning this to me?

you are good to go , thank you for your brief description , I appreciate your efforts . Let me know for any help!
