### ISSUE TITLE
Incomplete filter is not working properly

### ISSUE THREAD

**Issue by avinash201199** [avinash201199/To-Do-List#37]
![image](https://user-images.githubusercontent.com/61057666/135756794-ed02b8d1-0aa3-4614-bace-37e04762200f.png)

when we select incomplete filter then completed task is also visible 
comment to contribute will assign the issue

**Comment by OmGole** [comment]
Can I work on this?

**Comment by tanishk-23** [comment]
@avinash201199 can you assign this to me?
