### ISSUE TITLE
Delete All Button

### ISSUE THREAD

**Issue by Tejaswi-Chaudhari** [avinash201199/To-Do-List#41]
Hey @avinash201199 Can I work on the Delete all functionality?
Please assign this issue to me.

**Comment by avinash201199** [comment]
Don't forget to add screen shot in pr and issue number in pr heading

**Comment by Tejaswi-Chaudhari** [comment]
@avinash201199 
Please review PR #43 
Video added

**Comment by avinash201199** [comment]
> @avinash201199 Please review PR #43 Video added

great work :)
