### ISSUE TITLE
Bug - When reloading the page the task state changes to incomplete

### ISSUE THREAD

**Issue by sofiarm21** [avinash201199/To-Do-List#42]
When the app gets reloaded all the completed tasks go back to be in the incomplete state. Please  @avinash201199 assign me to this issue and make it part of Hacktoberfest

**Comment by avinash201199** [comment]
Don't forget to support your pr with screen shot

**Comment by ankitmittal99** [comment]
Hey, @avinash201199 Can I work on this bug (When reloading the page the task state changes to incomplete)?
Please assign this issue to me.

**Comment by sofiarm21** [comment]
@ankitmittal99 I'm already working on it
