### ISSUE TITLE
Prevent a task title exceeds display width

### ISSUE THREAD

**Issue by dynle** [avinash201199/To-Do-List#51]
Hello, @avinash201199 

For now, if I add a new task with a long title, it exceeds display width, which makes it users hard to read the title and click the buttons.

I think it would be better to add line-break to prevent it so that even if users write a task with a long title, they can read the title without scrolling.

If you think you need this, plz assign me this work!

![Screen Shot 2021-10-05 at 6 29 15 PM](https://user-images.githubusercontent.com/36508771/136001216-20fc28cf-37a7-4537-96ba-b262af64e5e8.png)

**Comment by avinash201199** [comment]
Go ahead :)
don't forget to add ss in pr
