### ISSUE TITLE
it is not resposive for phone

### ISSUE THREAD

**Issue by Hitanshuverma** [avinash201199/To-Do-List#76]
![image](https://user-images.githubusercontent.com/81898669/137622939-8fb1ba77-ebf9-449e-a969-df1d0627ac8a.png)
can I work on this issue

**Comment by Alam9835** [comment]
i have converted it to phone responsive.

**Comment by Alam9835** [comment]
any more changes are required?

**Comment by avinash201199** [comment]
please add screen shot

**Comment by Alam9835** [comment]
> please add screen shot

sure

**Comment by Alam9835** [comment]
![Screenshot 2021-10-19 124709](https://user-images.githubusercontent.com/88643897/137862060-471e44a3-8a6d-42bc-af5c-95c8a18a6a42.png)
