### ISSUE TITLE
Improving the UI and features of the to-do list

### ISSUE THREAD

**Issue by TishaJhabak1014** [avinash201199/To-Do-List#8]
There can be a lot of improvements in the part of color contrast and features in the to-do list.

@avinash201199 Let me know if I can add some.

**Comment by avinash201199** [comment]
@TishaJhabak1014 please don't forget to add screen shot

**Comment by TishaJhabak1014** [comment]
Can you please elaborate on where to add what screen shots.

**Comment by avinash201199** [comment]
screen shot of the updated ui in pull request

**Comment by TishaJhabak1014** [comment]
@avinash201199 Sir, I have a complete UI ready but facing problems adding events with javaScript. 
In the UI there are lots of different functionalities that can be added using JavaScript and I have added the various options for the same in the new UI for the to-do app, just contributions from Js experts can add multiple functionalities and bring them to live.

Let me know if you would like to see them.

**Comment by avinash201199** [comment]
> @avinash201199 Sir, I have a complete UI ready but facing problems adding events with javaScript. In the UI there are lots of different functionalities that can be added using JavaScript and I have added the various options for the same in the new UI for the to-do app, just contributions from Js experts can add multiple functionalities and bring them to life.
> 
> Let me know if you would like to see them.

yeah ,show

**Comment by TishaJhabak1014** [comment]
Yes sure, just give me 2 mins.

**Comment by TishaJhabak1014** [comment]
![Capture.PNG](https://user-images.githubusercontent.com/78808336/135728347-a3e891ed-23b7-4725-879f-34c133b4caa8.PNG)

**Comment by avinash201199** [comment]
@TishaJhabak1014 
It's completely different ,you worked a lot but I can't merge it .
you can work read on readme file small change is also accepted for you :)

**Comment by TishaJhabak1014** [comment]
> @TishaJhabak1014 
> It's completely different ,you worked a lot but I can't merge it .
> you can work read on readme file small change is also accepted for you :)
> 

@avinash201199 sure, just keep me assigned, I know what to do next. Thank you : )

**Comment by TishaJhabak1014** [comment]
@avinash201199 Added a small change to make the `All / completed/ Incomplete` a bit more consistent.

![Capture.PNG](https://user-images.githubusercontent.com/78808336/135743270-68cfb609-5d4f-4e54-80de-35784839edc3.PNG)
Let me know if you want to merge it.
