### ISSUE TITLE
Design new features or anything in your mind - comment down to get assigned 

### ISSUE THREAD

**Issue by avinash201199** [avinash201199/To-Do-List#88]

**Comment by rajputarjun2001** [comment]
Please assign me this PR

**Comment by rajputarjun2001** [comment]
Please assign me this issue

**Comment by keshav-rockwinder** [comment]
we can create a tickbox for a todo list. if you assign me this task

**Comment by uday03meh** [comment]
![image](https://user-images.githubusercontent.com/59679281/193456557-17b8b8c7-8a91-4996-8549-6282239b35c1.png)

We can add a hover class for all buttons to make it look more interactive to the user.
Can you assign me this issue?
