### ISSUE TITLE
🐛 Bug: Trim user input before adding into the list

### ISSUE THREAD

**Issue by mitpancholi98** [avinash201199/To-Do-List#99]
Steps
- enter item in input and add.
- enter same item with space (left / right) and add.

Able to enter same item with added spaces in input
![image](https://user-images.githubusercontent.com/51367069/193439447-03f5a6e1-d497-4f80-a362-eaa43b91e82b.png)

**Comment by mitpancholi98** [comment]
Hey there, can I continue ?

**Comment by avinash201199** [comment]
> Hey there, can I continue ?

sure
